---
linters:
  stylelint:
    config: 'stylelint.config.js'
    ignore: 'function-whitespace-after,function-parentheses-space-inside,function-comma-space-before,function-comma-space-after,color-hex-case'
